import logging
import os

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.routers import meta, query

logging.basicConfig(level=logging.INFO)

app = FastAPI(
    title="CollegeConnect AI API",
    description="Retrieval-augmented help desk: answers are generated by Claude from approved "
    "college documents (knowledge/) and returned with source citations.",
    version="0.2.0",
)

# Local dev: the Vite dev server runs on another port. On Vercel the frontend and API share
# one origin, so CORS isn't needed; ALLOWED_ORIGINS adds extra origins (comma-separated).
extra_origins = [o.strip() for o in os.getenv("ALLOWED_ORIGINS", "").split(",") if o.strip()]
app.add_middleware(
    CORSMiddleware,
    allow_origin_regex=r"http://(localhost|127\.0\.0\.1):\d+",
    allow_origins=extra_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(query.router)
app.include_router(meta.router)
